### PR TITLE
Add support for Laravel 11

### PR DESCRIPTION
**Pull request by jkudish**
Tweaked the dependencies so that the package can work with Laravel 11

### CODE REVIEW

**Comment by huzaifaarain** [comment]
@jkudish thanks

**Comment by jkudish** [comment]
Could you also publish a release @huzaifaarain ? :)

**Comment by huzaifaarain** [comment]
@jkudish  Sure

**Comment by huzaifaarain** [comment]
@jkudish v1.1.0 released. Thank you

**Pull request merged**
